feat: move storage skel for empty pvroot on first run to skel dir
* fix pv-appengine to install skel first thing if /storage is empty
* fix pv-appengine to prevent starting if the storage is not a mountpoint
* fix pantavisor-run.in from starting if /storage is not a mountpoint as well
* fix remount.c to look at cmake define to find the current json

diff --git a/pantavisor-run.in b/pantavisor-run.in
--- a/pantavisor-run.in
+++ b/pantavisor-run.in
@@ -2,6 +2,11 @@
 
 set -x
 
+if ! cat /proc/mounts | awk '{ print $2}' | grep '^@PV_INSTALL_FULL_STORAGEDIR@$'; then
+	echo "ERROR: @PV_INSTALL_FULL_STORAGEDIR@ must be a mountpoint."
+	sleep 10
+	exit 1
+fi
 
 mkdir -p /sys/fs/cgroup/pantavisor
 for pid in $(cat /sys/fs/cgroup/cgroup.procs); do
@@ -15,12 +20,7 @@ done
 mkdir -p /volumes
 mount --bind @CMAKE_INSTALL_RUNSTATEDIR@/pv/volumes /volumes
 
-mkdir -p /storage
-mount --bind @PV_INSTALL_FULL_STORAGEDIR@ /storage
-
 @CMAKE_INSTALL_FULL_BINDIR@/pantavisor $@
 
-umount /storage
-#umount /volumes
-#umount @CMAKE_INSTALL_RUNSTATEDIR@/pv/volumes
+umount /volumes
 
