set direct-io after loopback dev creation

diff --git a/scripts/volmount/verity/dm b/scripts/volmount/verity/dm
--- a/scripts/volmount/verity/dm
+++ b/scripts/volmount/verity/dm
@@ -70,6 +70,14 @@ do_mount_squash() {
 		return 3
 	fi
 
+	if ! _l=`losetup -a | grep "$container/$squashname)"$ | tail -n 1 | sed -e 's/:.*//'`; then
+		echo "ERROR: unable to setup loop device for $container/$squashname"
+		return 10
+	fi
+	if ! losetup --direct-io=on $_l; then
+		echo "ERROR: unable to setup direct-io flag for $_l"
+		return 11
+	fi
 }
 
 do_umount_squash() {
