improve scripts/volmount/crypt/crypt to be more robust against corruption
1. we will move to explicit .init_done marker file that we only place if whole do_crypt_init function has succeeded with changes synched to disk
2. we only do losetup logic for dm_type caam
3. we create a .goodbak copy of the image file every time we successfully finish with do_mount_disk; we are extra careful and create a .prebak copy of the image file before the mounting happens.
4. we make do_mount_disk try the following before giving up:
    - mount crypt disk as usual
    - if fails run an fsk.ext4 -y on that /dev/mapper/ device
    - if that fails we put back the .goodbak file (if such exist)
   at code we do this through recursive invocation of the do_mount_disk function with a 4th parameter 'specialrun' mode

Also we change the volumes.c mount code to properly fail if any error code is returned by crypt helper so we dont boot into a system without crypt disk

diff --git a/scripts/volmount/crypt/crypt b/scripts/volmount/crypt/crypt
--- a/scripts/volmount/crypt/crypt
+++ b/scripts/volmount/crypt/crypt
@@ -30,14 +30,6 @@ mntpath=$4
 
 CAAM_KEYGEN=/usr/bin/caam-keygen
 
-do_find_free_loop()
-{
-	FREE_LOOP=`/sbin/losetup -f`
-	if [ -n "$FREE_LOOP" ]; then
-		return 0;
-	fi
-}
-
 do_crypt_init()
 {
 	base=`basename $1`
@@ -66,17 +58,23 @@ do_crypt_init()
 		exit 1
 	fi
 
+	# sync after keyname files got created
+	sync
+
 	img_file=`echo $base | awk '{split($0,a,","); print a[1]}'`
 	img_size=`echo $base | awk '{split($0,a,","); print a[2]}'`
 	/bin/dd if=/dev/zero of=$dir/$img_file bs=1M count=$img_size
-	do_find_free_loop
 
-	/sbin/losetup -f $dir/$img_file
-	[ $? -ne 0 ] && echo "ERROR: Unable to loop setup" && exit 1
+	if [ $dm_type == "caam" ]; then
+		if ! CAAM_LOOP=`/sbin/losetup -f $dir/$img_file`; then
+			echo "ERROR: Unable to loop setup"
+			exit 1
+		fi
+	fi
 
 	device_name=`echo $img_file | awk '{split($0,a,"."); print a[1]}'`
 	if [ $dm_type == "caam" ]; then
-		/usr/sbin/dmsetup -v create $device_name --table "0 $(/sbin/blockdev --getsz $FREE_LOOP) crypt capi:tk(cbc(aes))-plain :36:logon:logkey: 0 $FREE_LOOP 0 1 sector_size:512"
+		/usr/sbin/dmsetup -v create $device_name --table "0 $(/sbin/blockdev --getsz $CAAM_LOOP) crypt capi:tk(cbc(aes))-plain :36:logon:logkey: 0 $CAAM_LOOP 0 1 sector_size:512"
 	elif [ $dm_type == "dcp" ]; then
 		/usr/sbin/cryptsetup open -s 256 -c "capi:cbc(aes)-essiv:sha256" --type plain --key-file=$dir/$keyname.bb $dir/$img_file $device_name
 	elif [ $dm_type == "versatile" ]; then
@@ -90,11 +88,13 @@ do_crypt_init()
 	/usr/sbin/mkfs.ext4 /dev/mapper/$device_name
 	[ $? -ne 0 ] && echo "ERROR: Unable to format to ext4" && exit 1
 
+	sync
 	if [ $dm_type == "caam" ]; then
 		/usr/sbin/dmsetup remove $device_name
 		/bin/keyctl clear @u
 		/bin/keyctl purge @u
 		rm -rf /data
+		/sbin/losetup -d $CAAM_LOOP
 	elif [ $dm_type == "dcp" ]; then
 		/usr/sbin/cryptsetup close $device_name
 	elif [ $dm_type == "versatile" ]; then
@@ -104,7 +104,8 @@ do_crypt_init()
 		exit 1
 	fi
 
-	/sbin/losetup -d $FREE_LOOP
+	sync
+	touch $dir/$keyname.init_done
 }
 
 do_dm_sanity()
@@ -134,11 +135,16 @@ do_mount_disk()
 {
 	do_dm_sanity
 
+	dm_type=$1
+	path=$2
+	mntpath=$3
+	specialrun=$4
+
 	base=`basename $2`
 	dir=`dirname $2`
 
 	keyname=`echo $base | awk '{split($0,a,","); print a[3]}'`
-	[ ! -f $dir/$keyname.bb ] && do_crypt_init $2
+	[ ! -f $dir/$keyname.init_done ] && do_crypt_init $2
 
 	cd $dir
 	if [ $dm_type == "caam" ]; then
@@ -152,15 +158,15 @@ do_mount_disk()
 	fi
 
 	img_file=`echo $base | awk '{split($0,a,","); print a[1]}'`
-	do_find_free_loop
-	if ! /sbin/losetup -f $dir/$img_file; then
+	cp -f $dir/$img_file $dir/$img_file.prebak
+	if ! CAAM_LOOP=`/sbin/losetup -f $dir/$img_file`; then
 		echo "ERROR: could not loosetup"
 		return 1;
 	fi
 
 	device_name=`echo $img_file | awk '{split($0,a,"."); print a[1]}'`
 	if [ $dm_type == "caam" ]; then
-		/usr/sbin/dmsetup create $device_name --table "0 $(/sbin/blockdev --getsz $FREE_LOOP) crypt capi:tk(cbc(aes))-plain :36:logon:logkey: 0 $FREE_LOOP 0 1 sector_size:512"
+		/usr/sbin/dmsetup create $device_name --table "0 $(/sbin/blockdev --getsz $CAAM_LOOP) crypt capi:tk(cbc(aes))-plain :36:logon:logkey: 0 $CAAM_LOOP 0 1 sector_size:512"
 	elif [ $dm_type == "dcp" ]; then
 		/usr/sbin/cryptsetup open -s 256 -c "capi:cbc(aes)-essiv:sha256" --type plain --key-file=$dir/$keyname.bb $dir/$img_file $device_name
 	elif [ $dm_type == "versatile" ]; then
@@ -169,18 +175,52 @@ do_mount_disk()
 		echo "Unknown device mapper target"
 		exit 1
 	fi
-	[ $? -ne 0 ] && echo "ERROR: $dm_type: Unable to create/open crypt device" && exit 1
+	if [ $? -ne 0 ]; then
+		echo "ERROR: $dm_type: Unable to create/open crypt device"
+		exit 1
+	fi
 
 	if [ ! -b /dev/mapper/$device_name ]; then
-		echo "ERROR: could not crypt mapper"
-		return 2;
+		echo "ERROR: could not find the matching crypt mapper device /dev/mapper/$device_name"
+		return 2
 	fi
 
 	mkdir -p $3
-	if ! mount /dev/mapper/$device_name $3; then
-		echo "ERROR: could not setup dm-crypt volume"
-		return 3;
+	if mount /dev/mapper/$device_name $3; then
+		# only backup if a clean run success
+		[ -z "$specialrun" ] && cp -f $dir/$img_file.prebak $dir/$img_file.goodbak
+		sync
+		return 0
 	fi
+
+	echo "ERROR: could not setup dm-crypt volume"
+	if [ "$specialrun" == "fsck" ] && [ -f $dir/$img_file.goodbak ]; then
+		echo "Specialrun $specialrun did not succeed ... trying from goodbackup"
+		cp -f $dir/$img_file.goodbak $dir/$img_file
+		/usr/sbin/cryptsetup close $device_name || true
+		if ! do_mount_disk "$dm_type" "$path" "$mntpath" bak; then
+			return $?;
+		fi
+		echo "do_mount_disk from backup suceeded..."
+		return 0
+	elif [ "$specialrun" == "fsck" ]; then
+		# later here we could remove .init_done file to trigger full reinit on next powercycle
+		echo "do_mount_disk failed, no backup available, giving up!"
+		return 5
+	elif [ "$specialrun" == "bak" ]; then
+		# later here we could remove .init_done file to trigger full reinit on next powercycle
+		echo "do_mount_disk specialrun 'bak' failed. giving up ..."
+		return 6
+	fi
+
+	echo "Trying fsck ...."
+	/usr/sbin/fsck.ext4 -y /dev/mapper/$device_name || true
+	/usr/sbin/cryptsetup close $device_name || true
+	sync
+	if ! do_mount_disk "$dm_type" "$path" "$mntpath" fsck; then
+		return $?
+	fi
+	return 0
 }
 
 do_umount_disk()
