set direct-io after loopback dev creation

diff --git a/scripts/volmount/crypt/crypt b/scripts/volmount/crypt/crypt
--- a/scripts/volmount/crypt/crypt
+++ b/scripts/volmount/crypt/crypt
@@ -52,11 +52,16 @@ atomic_losetup()
 		echo "ERROR: unable to setup loop device for $_imgfile"
 		return 122
 	fi
-	if ! _l=`losetup -a | grep ${imgfile}$ | tail -n 1`; then
+	if ! _l=`losetup -a | grep ${imgfile}$ | tail -n 1 | sed -e 's/:.*//'`; then
 		echo "ERROR: unable to setup loop device for $_imgfile"
 		return 122
 	fi
-	echo $_l | sed -e 's/:.*//'
+	if ! losetup --direct-io=on $_l; then
+		echo "ERROR: unable to setup direct-io flag for $_l"
+		return 122
+	fi
+
+	echo $_l
 }
 
 do_crypt_init()
diff --git a/scripts/volmount/verity/dm b/scripts/volmount/verity/dm
--- a/scripts/volmount/verity/dm
+++ b/scripts/volmount/verity/dm
@@ -63,6 +63,7 @@ do_mount_squash() {
 		return 2
 	fi
 
+	losetup -a
 
 	mkdir -p $volpath
 	if ! mount -oloop /dev/mapper/$dmname $volpath; then
@@ -70,6 +71,18 @@ do_mount_squash() {
 		return 3
 	fi
 
+	echo "searching loopback device from $container/$squashname"
+
+	if ! _l=`losetup -a | grep "$container/$squashname)"$ | tail -n 1 | sed -e 's/:.*//'`; then
+		echo "ERROR: unable to setup loop device for $container/$squashname"
+		return 10
+	fi
+	if ! losetup --direct-io=on $_l; then
+		echo "ERROR: unable to setup direct-io flag for $_l"
+		return 11
+	fi
+
+	losetup -a
 }
 
 do_umount_squash() {
