style: fix formatting in appengine and pvtest scripts

diff --git a/appengine/pv-appengine.in b/appengine/pv-appengine.in
--- a/appengine/pv-appengine.in
+++ b/appengine/pv-appengine.in
@@ -25,17 +25,18 @@ cleanup_cgroup() {
 	fi
 }
 
-	setup_loop() {
-		local count="$1"
-		local first="$(losetup -f | grep -oE '[0-9]+$')"
-		first=$((first + 1))
+setup_loop() {
+	local count="$1"
+	local first="$(losetup -f | grep -oE '[0-9]+$')"
+	first=$((first + 1))
 
-		for i in $(seq "$first" "$((first + count))"); do
-			mknod -m660 "/dev/loop$i" b 7 "$i" > /dev/null 2>&1 || true
-		done
+	for i in $(seq "$first" "$((first + count))"); do
+		mknod -m660 "/dev/loop$i" b 7 "$i" > /dev/null 2>&1 || true
+	done
 
-		echo "$first"
-	}
+	echo "$first"
+}
+
 teardown_loop() {
 	local first="$1"
 	local count="$2"
@@ -45,24 +46,25 @@ teardown_loop() {
 	done
 }
 
-	exec_run() {
-		# get installation path
-		scriptpath=`readlink -f "$0"`
+exec_run() {
+	# get installation path
+	scriptpath=`readlink -f "$0"`
 
-		# check installed
-		if [ ! -f "@CMAKE_INSTALL_FULL_SYSCONFDIR@/pantavisor-appengine.config" ]; then
-			echo "ERROR: installation path '@CMAKE_INSTALL_FULL_SYSCONFDIR@/pantavisor-appengine.config' not found"
-			exit 1
-		fi
+	# check installed
+	if [ ! -f "@CMAKE_INSTALL_FULL_SYSCONFDIR@/pantavisor-appengine.config" ]; then
+		echo "ERROR: installation path '@CMAKE_INSTALL_FULL_SYSCONFDIR@/pantavisor-appengine.config' not found"
+		exit 1
+	fi
 
-		if ! cat /proc/mounts | awk '{ print $2}' | grep -q '^@PV_INSTALL_FULL_STORAGEDIR@$'; then
-			echo "WARN: @PV_INSTALL_FULL_STORAGEDIR@ is not a mountpoint. Automatic installation might fail."
-		fi
+	if ! cat /proc/mounts | awk '{ print $2}' | grep -q '^@PV_INSTALL_FULL_STORAGEDIR@$'; then
+		echo "WARN: @PV_INSTALL_FULL_STORAGEDIR@ is not a mountpoint. Automatic installation might fail."
+	fi
 
-		if ! [ -f @PV_INSTALL_FULL_STORAGEDIR@/.created ]; then
-			cp -a @PV_INSTALL_FULL_SKELDIR@/* @PV_INSTALL_FULL_STORAGEDIR@/ || true
-			touch @PV_INSTALL_FULL_STORAGEDIR@/.created || true
-		fi
+	if ! [ -f @PV_INSTALL_FULL_STORAGEDIR@/.created ]; then
+		cp -a @PV_INSTALL_FULL_SKELDIR@/* @PV_INSTALL_FULL_STORAGEDIR@/ || true
+		touch @PV_INSTALL_FULL_STORAGEDIR@/.created || true
+	fi
+
 	if ! [ -f @PV_INSTALL_FULL_STORAGEDIR@/.pvtx-done ]; then
 		pvtx abort
 		pvtx begin @PV_INSTALL_FULL_STORAGEDIR@/trails/0 @PV_INSTALL_FULL_STORAGEDIR@/objects
@@ -87,8 +89,7 @@ teardown_loop() {
 	shutdown=0
 	trap 'shutdown=1; echo "Recevied SIGINT, shutting down pantavisor ..."' SIGINT
 
-	while [ "$shutdown" -eq 0 ]
-	do
+	while [ "$shutdown" -eq 0 ]; do
 		# load boot info
 		revs=`cat "@PV_INSTALL_FULL_STORAGEDIR@/boot/uboot.txt"`
 		pv_rev=`echo "$revs" | awk -v FS="(pv_rev=|pv_try=)" '{print $2}'`
@@ -100,7 +101,7 @@ teardown_loop() {
 				pv_trying=""
 			else
 				pv_trying="$pv_try"
-				pv_rev="$pv_try";
+				pv_rev="$pv_try"
 			fi
 		fi
 
@@ -153,26 +154,27 @@ teardown_loop() {
 # parse options
 while [ $# -gt 0 ]; do
 	case "$1" in
-		-h)
-			usage; exit 0
-			;;
-		-i)
-			interactive='true'
-			;;
-		-c)
-			shift
-			cmdline="$1"
-			;;
-		-e)
-			shift
-			envs="$1"
-			;;
-		*)
-			break
+	-h)
+		usage
+		exit 0
+		;; 
+	-i)
+		interactive='true'
+		;; 
+	-c)
+		shift
+		cmdline="$1"
+		;; 
+	-e)
+		shift
+		envs="$1"
+		;; 
+	*)
+		break
+		;; 
 	esac
 	shift
 done
 
 # uninstall Pantavisor
 exec_run
-
diff --git a/pvtest/pvtest-run.in b/pvtest/pvtest-run.in
--- a/pvtest/pvtest-run.in
+++ b/pvtest/pvtest-run.in
@@ -116,16 +116,16 @@ stop_pv() {
 	if [ -n "$pv_pid" ]; then
 		eval "pventer -c $control_container pvcontrol commands poweroff" > /dev/null 2>&1
 		wait_for_process " pantavisor$" "120" "-d"
+		if [ $? -ne 0 ]; then
+			echo "Warn: Pantavisor still running. Shutting it down..."
+			kill "$pv_pid"
+			wait_for_process " pantavisor$" "30" "-d"
 			if [ $? -ne 0 ]; then
-				echo "Warn: Pantavisor still running. Shutting it down..."
-				kill "$pv_pid"
-				wait_for_process " pantavisor$" "30" "-d"
-				if [ $? -ne 0 ]; then
-					echo "Error: Pantavisor still running. Exiting..."
-					kill -SIGKILL "$pv_pid"
-					pv_ready="false"
-				fi
+				echo "Error: Pantavisor still running. Exiting..."
+				kill -SIGKILL "$pv_pid"
+				pv_ready="false"
 			fi
+		fi
 	fi
 }
 
@@ -148,7 +148,7 @@ start_pv() {
 
 	wait_for_process " pantavisor$" "30" "-a"
 	if [ $? != 0 ]; then
-	echo "Error: timed out waiting for Pantavisor PID"
+		echo "Error: timed out waiting for Pantavisor PID"
 		return
 	fi
 
@@ -162,7 +162,7 @@ start_pv() {
 
 	wait_for_value "pventer -c $control_container pvcontrol devmeta ls | jq -r .'[\"pantavisor.status\"]'" "READY" "120"
 	if [ $? != 0 ]; then
-	echo "Error: timed out waiting for pantavisor.status READY"
+		echo "Error: timed out waiting for pantavisor.status READY"
 	else
 		pv_ready="true"
 	fi
